:sparkles: feat: add spellcheck ci
LearningTypeScript/projects pull request #96
Opened 2022-06-18 17:20 UTC by fuadop

## PR Checklist

- [x] Addresses an existing open issue: fixes #8 
- [x] That issue was marked as [accepting prs](https://github.com/LearningTypeScript/projects/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/LearningTypeScript/projects/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

 uses cspell for spellcheck on projects directory.

2022-06-18 18:07 UTC, JoshuaKGoldberg commented on .github/workflows/spellcheck.yml
> +        run: npx cspell lint projects/**/*.{ts,md,js} --show-suggestions
<details>
<summary>There are a ton of false positives getting logged on code files. Examples inside.</summary>

```plaintext
 13/221 ./projects/arrays/text-processor/src/index.test.ts 458.14ms X
/home/runner/work/projects/projects/projects/arrays/text-processor/src/index.test.ts:66:17 - Unknown word (abcdefghi) Suggestions: []
/home/runner/work/projects/projects/projects/arrays/text-processor/src/index.test.ts:66:61 - Unknown word (abcdefghi) Suggestions: []
```

```plaintext
 33/221 ./projects/configuration-options/secret-messages/01-encoded-outputs/index.verify.ts 316.61ms X
/home/runner/work/projects/projects/projects/configuration-options/secret-messages/01-encoded-outputs/index.verify.ts:12:14 - Unknown word (mkstx) Suggestions: [mktx, MKTX, masts, misti, mists]
/home/runner/work/projects/projects/projects/configuration-options/secret-messages/01-encoded-outputs/index.verify.ts:13:15 - Unknown word (uytm) Suggestions: [yum, ubyte, ulta, unto, upto]
```

```plaintext
/home/runner/work/projects/projects/projects/type-operations/template-literal-type-shenanigans/03-split-on/index.test.ts:7:46 - Unknown word (bbaabb) Suggestions: [babas, baba, baobab, blabby, baa's]
/home/runner/work/projects/projects/projects/type-operations/template-literal-type-shenanigans/03-split-on/index.test.ts:8:42 - Unknown word (bbaabb) Suggestions: [babas, baba, baobab, blabby, baa's]
/home/runner/work/projects/projects/projects/type-operations/template-literal-type-shenanigans/03-split-on/index.test.ts:9:48 - Unknown word (ababa) Suggestions: [abba, abaca, aqaba, Abba, Aqaba]
```
</details>

Do you see a lot of benefit in running on `.ts` and `.js` files?

2022-06-18 18:08 UTC, JoshuaKGoldberg requested changes
Thanks for sending this in! There are a lot of [failures in CI](https://github.com/LearningTypeScript/projects/runs/6949577086?check_suite_focus=true) right now so we'll have to avoid/fix them in some way.

2022-07-23 16:32 UTC, JoshuaKGoldberg commented
👋 @fuadop just checking in, is this still something you have time to look into?

No worries if not, just making sure the issue isn't blocked! 😄

2022-07-27 06:24 UTC, fuadop commented
Hey @JoshuaKGoldberg 👋 , super sorry about the delay.

About this, the words truly aren't existent, Do we create a dictionary file? but that's what we are trying to avoid here right?

2022-07-27 14:13 UTC, JoshuaKGoldberg commented
Hmm yeah, it is unfortunate how many words are being flagged right now. How about including only `.md` files in the spellcheck check? There are only two `.md` failures right now, both of which should go away once the [`typescript` dictionary](https://cspell.org/docs/dictionaries/#programming-language-dictionaries) is [configured to be used](https://cspell.org/docs/getting-started/#1-create-a-configuration-file).

2022-08-07 19:38 UTC, fuadop commented
Hey @JoshuaKGoldberg,
I am actually seeing more than two words being flagged for `.md` files on my end 🤔.

![image](https://user-images.githubusercontent.com/65264054/183308127-9b65627b-ddc6-431b-8a91-d7814ac9b12b.png)

2022-08-07 19:51 UTC, JoshuaKGoldberg commented
Hmm, is that with the TypeScript dictionary enabled? If so: I probably did it wrong on my end then 😄.

2022-08-07 19:53 UTC, fuadop commented
With the typescript dictionary, it reduced to 37 from 42. 
![image](https://user-images.githubusercontent.com/65264054/183308822-3b70322f-64ba-49ad-9b69-52426db94f8e.png)

2022-08-07 20:20 UTC, JoshuaKGoldberg commented
Heh. Well, there are a lot of custom words in this repo: Typarium, Typespeare, etc. I think it makes sense that we'd have to add a dictionary.

If that's a lot more work than you have time for, I can always take over - no worries!

2022-08-07 20:26 UTC, fuadop commented
Yea, I can add that. how would you love the dictionary file to be stored in the repo? is the dictionary file okay in the root directory?

2022-08-07 20:28 UTC, JoshuaKGoldberg commented
Yeah that makes sense! If you have opinions on a better way I'd be interested though 😄.

2022-08-16 15:49 UTC, JoshuaKGoldberg commented on projects/type-modifiers/modifiers-of-the-types/02-artifact-assertions/characters.ts
> +        "powers": ["telekinesis", "telepathy", "teleportation"],
Nice 😄 spellcheck really is useful!

2022-08-16 15:51 UTC, JoshuaKGoldberg approved these changes
Wonderful, thanks for this @fuadop! ✨

2022-08-16 15:51 UTC, merged